apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-cloud-default: "true"
        io.kompose.service: grafana-server
    spec:
      containers:
        - image: {{.Values.ecr}}:grafana-server
          name: grafana-server
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources:
            limits:
              memory: "268435456"
      restartPolicy: Always