apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-api-gateway
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace : {{ .Values.namespace}}
spec:
  type: {{ .Values.api_gateway.service.type }}
  ports:
    - port: {{ .Values.api_gateway.service.port }}
      targetPort: {{ .Values.api_gateway.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app : api-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-customers-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace : {{ .Values.namespace}}
spec:
  type: {{ .Values.customers_service.service.type }}
  ports:
    - port: {{ .Values.customers_service.service.port }}
      targetPort: {{ .Values.customers_service.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app : customers-service

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-vets-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace : {{ .Values.namespace}}
spec:
  type: {{ .Values.vets_service.service.type }}
  ports:
    - port: {{ .Values.vets_service.service.port }}
      targetPort: {{ .Values.vets_service.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app : vets-service

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-visits-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace : {{ .Values.namespace}}
spec:
  type: {{ .Values.visits_service.service.type }}
  ports:
    - port: {{ .Values.visits_service.service.port }}
      targetPort: {{ .Values.visits_service.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app : visits-service