apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: customers-db-mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.customers_db_mysql.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: customers-db-mysql
        image: {{ .Values.customers_db_mysql.image }}
        ports:
        - containerPort: {{ .Values.customers_db_mysql.service.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customers-db-mysql
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value : customers-db-mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vets-db-mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.vets_db_mysql.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: vets-db-mysql
        image: {{ .Values.vets_db_mysql.image }}
        ports:
        - containerPort: {{ .Values.vets_db_mysql.service.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vets-db-mysql
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value : vets-db-mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: visits-db-mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.visits_db_mysql.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: visits-db-mysql
        image: {{ .Values.visits_db_mysql.image }}
        ports:
        - containerPort: {{ .Values.visits_db_mysql.service.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: visits-db-mysql
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value : visits-db-mysql